### ISSUE TITLE
M5Stack CoreS3へのWebからの書き込みに失敗します

### ISSUE THREAD

**Issue by meganetaaan** [rt-net/stack-chan#1]
**不具合の概要**
M5Stack CoreS3へのWebからのファームウェア書き込みに失敗します。

**再現手順**
不具合を再現できる手順を記述してください
1. https://rt-net.github.io/stack-chan/web/flash にアクセスする
2. M5Stack CoreS3を選択して書き込みを行う
3. エラーが発生して書き込みが始まらない

**想定する挙動**
M5Stack CoreS3にファームウェアを書き込める

**その他**

ししかわ版ｽﾀｯｸﾁｬﾝで既知の不具合であり、ししかわ版では修正済みです。
修正のコミットをこちらにも取り込めば治るはずです。

https://github.com/stack-chan/stack-chan/pull/247

**Comment by KuraZuzu** [comment]
ししかわ版ｽﾀｯｸﾁｬﾝの既知の問題での修正点で必要なファイルをを取り込み、フォーマットも修正しました。

PR: https://github.com/rt-net/stack-chan/pull/2

この後、`gh-pages`のブランチを切る操作をすれば https://rt-net.github.io/stack-chan/web/flash にアクセスしての書き込み環境が整うはずです。

**Comment by KuraZuzu** [comment]
PR: https://github.com/rt-net/stack-chan/pull/2 が取り込まれ、`gh-pages`ブランチの作成と設定により https://rt-net.github.io/stack-chan/web/flash にアクセスしてM5Stack CoreS3 の認識まで完了しました。

ですが、ファームウェアを書き込もうとすると以下のようなエラーが出力されます。

```
Installation failed

Downlading firmware tech.moddable.stackchan/com.m5stack.cores3/bootloader.bin failed: 404
```

![image_2024_5_15](https://github.com/rt-net/stack-chan/assets/60168333/9ae9cb5a-00da-4900-92e6-bd2d4e8b0e3f)

**Comment by KuraZuzu** [comment]
bundle.ymlに記述されたビルドとデプロイ対象のブランチがししかわ版ｽﾀｯｸﾁｬﾝの`dev/v1.0`のままだったため、`main`に変更しました（PR: https://github.com/rt-net/stack-chan/pull/3 , PR: https://github.com/rt-net/stack-chan/pull/4 ）。

`M5Stack CoreS3`へのｽﾀｯｸﾁｬﾝファームウェアの書き込み成功を確認しました。
